# Generated by Django 4.0.4 on 2022-06-01 21:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_csv', models.FileField(storage=api.models.CustomStorage(), upload_to='')),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('file_columns', models.TextField(blank=True)),
            ],
        ),
    ]
